### ISSUE TITLE
null geometry should be handled

### ISSUE THREAD

**Issue by stf8** [perliedman/reproject#12]
Hi, 

it appears quite a lot geojson producers output records with a "geometry":null  , currently reproject crashes on that, as it expects to have at least an object with a type property.

A small fix would be to ignore those records, as hopefully they can be left as. This can be done using such a condition in traverseGeoJson  : 

`if (geojson.type === 'Feature' && geojson.geometry!== null)`

and later on, in the leafCallback, checking that there are coordinates to traverse.

Regards,

Stéphane

**Comment by perliedman** [comment]
Hi and many thanks for reporting!

Leaving `geometry` set to `null` is indeed valid according to the GeoJSON spec.

I've fixed this and released version 1.1.1 which contains the fix.
