### ISSUE TITLE
Does not remove `crs` field in feature collection

### ISSUE THREAD

**Issue by gabssnake** [perliedman/reproject#14]
The `crs` field is not removed for a feature collection, it is however removed for a on a single point feature.

To reproduce :

```
cat sample.json | reproject --use-spatialreference --from=EPSG:27562 --to=EPSG:4326 > output.json
```

Output will not contain `crs` field (expected behaviour) :

``` json
{
    "type": "Point",
    "coordinates": [
        947102.26318226,
        74033.812695628
    ],
    "crs": {
        "type": "name",
        "properties": {
            "name": "EPSG:27562"
        }
    }
}
```

Output will still contain `crs` field (expected?) :

``` json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Point",
      "coordinates": [
        947102.26318226,
        74033.812695628
      ]
    }
  ],
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:27562"
    }
  }
}
```

**Comment by perliedman** [comment]
Sorry about a _really_ late reply, but I think this is, at the core, same issue as #34. I've tested your example with the changes the branch linked in that issue, and with these changes `crs` is not part of the result.

So, when I'm merging that fix, I hope to close this issue as well!

**Comment by gabssnake** [comment]
Thank you for your answer. That makes sense!
I'd be happy to add a test case for the `crs` as soon as #34 lands.
