### ISSUE TITLE
Use geojson-stream instead of concat-stream

### ISSUE THREAD

**Issue by anandthakker** [perliedman/reproject#15]
@perliedman Thanks for this super handy lib!

Would you be open to a PR that replaces the use of `concat-stream` in `cli.js` with something like [`geojson-stream`](https://github.com/mapbox/geojson-stream)?  The idea/benefit would be to avoid buffering a very large geojson input in memory, instead reprojecting it one feature at a time.

**Comment by perliedman** [comment]
Hi,
that sounds clever. As long as the changes can be kept in `cli.js` (or at least mostly in there), I would love to see it!
