### ISSUE TITLE
Replace SpatialReference.org with something more up-to-date

### ISSUE THREAD

**Issue by maxharlow** [perliedman/reproject#21]
SpatialReference.org hasn't been updated since 2013, and doesn't have popular systems such as the modern reference for Web Mercator (EPSG:3857). Perhaps we could use something more up-to-date like [EPSG.io](https://epsg.io/) instead/in addition?

**Comment by perliedman** [comment]
Hi, this sounds like a great idea. A PR would be welcome.

**Comment by derhuerst** [comment]
What about using [`epsg-index`](https://github.com/derhuerst/epsg-index)? I just built it with the intent of having an offline index. I may also create another npm package that fetches a `proj4` string from `epsg.io` on the fly.
