### ISSUE TITLE
Proj4js 2.4 compatibility

### ISSUE THREAD

**Issue by geoloep** [perliedman/reproject#24]
Reproject allows Proj4js 2.4 to be installed as an dependency but in my setup it is not compatible with it. Proj4js switched to ES6 style modules and now exports a default object. This results in a "TypeError: proj4.Proj is not a function" error in the determineCrs function of reproject for me. The Proj function is now under proj4.default.Proj. Reverting to proj4js 2.3 resolved the problem for now. I'm using webpack to create my bundle.

**Comment by perliedman** [comment]
This sounds an awful lot like https://github.com/kartena/Proj4Leaflet/issues/139; the bottom line is that this is some webpack related issue, and not an issue with proj4js an reproject, they still work fine with Node and for example Browserify.

If you're convinced that this is not Webpack's fault, I think you should raise an issue with proj4js to make sure they package the module in a way that works with Webpack as well. As for reproject, it's only in the middle of this, and enforcing an outdated version of proj4js seems like a bad idea.

**Comment by geoloep** [comment]
That's fair. I should have looked a little deeper. Thanks for taking the time to respond and for creating this very helpful tool!
