### ISSUE TITLE
Coordinate dimensions other than XY fails

### ISSUE THREAD

**Issue by rotsee** [perliedman/reproject#27]
It seems like the only coordinate dimensions that work are XY (not e.g. XYZ, XYM). Not sure this that is a bug or a feature not yet implemented. For XYZ- coordinates the script fails with the error `TypeError: coordinates.map is not a function` at `/reproject/index.js:13:22`

**Comment by perliedman** [comment]
Hi, could you supply an example where this goes wrong?

I had a quick look at the code and found that we have made some work for this, with simple tests as well (https://github.com/perliedman/reproject/commit/c711a4a23b5afbe6a2f7be688a85b2715f8cfd74), but apparently there's something missing.

**Comment by rotsee** [comment]
Here's a minimal example not working for me (NodeJS 8.9.3, Reproject 1.1.1):

```
> const {reproject} = require("reproject")
> let epsg = {
...     'EPSG:4326': "+proj=longlat +datum=WGS84 +no_defs",
...     'EPSG:21781': "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +towgs84=674.4,15.1,405.3,0,0,0,0 +units=m +no_defs",
... }
> reproject({"type":"Point","coordinates":[10,54,2850]}, "EPSG:4326", "EPSG:21781", epsg)
TypeError: coordinates.map is not a function

> reproject({"type":"Point","coordinates":[10,54,2850]}, "EPSG:4326", "EPSG:4326", epsg)
TypeError: coordinates.map is not a function
```

Here's a real geojson object that gives the same error: http://api.thenmap.net/v1/ch-8/geo/2018

(Wouldn't be surprised if it me who is doing something wrong here)

**Comment by perliedman** [comment]
Hm, that's odd... Check this out (Node 8.0.0, reproject from `master`, which doesn't look like it has any signigicant changes to 1.1.1):

```
$ node                                                                                 
> var {reproject} = require('./')            
undefined
> let epsg = {                                                                         
...     'EPSG:4326': "+proj=longlat +datum=WGS84 +no_defs",                            
...     'EPSG:21781': "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +
k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +towgs84=674.4,15.1,405.3,0,0,0,0 +units=m 
+no_defs",                                                                             
... }                                                                                  
undefined                                                                              
> reproject({"type":"Point","coordinates":[10,54,2850]}, "EPSG:4326", "EPSG:21781", epsg)
{ type: 'Point',                                                                       
  coordinates: [ 769223.1938420103, 988876.1737116188, -23.436734860762954 ] }         
>                                                                                      
Spiskummin+per@Spiskummin MINGW32 ~/Documents/Projects/reproject                       
$ node --version                                                                       
v8.0.0
```

So it "works", but I can also see that the Z-component of the coordinate is transformed; don't know if this is something you expect?

**Comment by rotsee** [comment]
Let me try and reproduce from a clean install, and see what happens!

**Comment by perliedman** [comment]
For the record, I also successfully reprojected the GeoJSON from the URL you pasted above to EPSG:21781.

(I guess you have already noticed that the URL itself points to something that isn't valid GeoJSON, but it wraps a valid GeoJSON object that can be reprojected.)

**Comment by rotsee** [comment]
I've tried again now on a clean install, and it works just fine (maybe there was some weird npm caching thing going on?), so closing this issue. Thanks for looking into it, and sorry for taking your time.

**Comment by perliedman** [comment]
:+1: No worries, this pushed me into finally refactoring some parts of the lib, so all good!
