### ISSUE TITLE
Z dimension gets converted into undefined/null

### ISSUE THREAD

**Issue by stevage** [perliedman/reproject#40]
Reprojecting a source file with z coordinates results in them being turned into `undefined`, which get serialised to `null`, which is not valid geojson.

Example here: https://runkit.com/stevebennett/5bf0eb81237f9f0012baa2d0

Coordinates other than X/Y should be left alone.

**Comment by perliedman** [comment]
Agreed.

The problem seems to be that we are passing along the whole coordinate array to Proj4, which presumably sets `undefined` for the axis it does not no about: https://github.com/perliedman/reproject/blob/master/index.js#L104

**Comment by stevage** [comment]
Ok I've submitted a PR. There's a weird thing where there is an existing test case which actually wasn't being evaluated correctly, and in fact it fails. The Z coordinate in the "retains altitude" test case is actually coming out as -38.2270, not 10, as the test expects. I don't know whether the test case is simply mistaken, or what's going on.

**Comment by perliedman** [comment]
Huh, that's interesting. I know I set up the tests a long time ago, when my JS skills where pretty limited, so it might well be that it actually does not work. I will try to look into it!

**Comment by perliedman** [comment]
Fixed the broken test and released with your changes as 1.2.3 :tada: 

Also invited you as a collaborator, seems you are using this project at least as much as I do!
