### ISSUE TITLE
Can I use it in my web app?

### ISSUE THREAD

**Issue by MrGorki** [perliedman/reproject#8]
I saw it is in javascript but don't know how to use it in my web app. Is it possible?

**Comment by perliedman** [comment]
Yes, I use it in several apps. Having said that, it's written following the CommonJS standard, which means the script can't be loaded directly in the browser.

I usually use [Browserify](http://browserify.org/) to package reproject, and other CommonJS modules, for the browser. There are some other options as well. You should check it out, it really makes handling JavaScript and modules in the browser a lot easier!
